variable "oci_tenancy" {}
variable "app_subnets" {}
variable "bastion_subnets" {}
variable "lb_subnets" {}
variable "compartments_output" {}
variable "vcns" {}
variable "vcn_rts" {}
variable "igws" {}
variable "lb_output" {}
variable "compute_bastions_output" {}
