#!/bin/bash
"sudo apt-get update"
"sudo apt install snapd"
"sudo snap install oracle-cloud-agent --classic"
"echo '****************** Installing Docker ******************'"
"sudo apt-get install -y apt-transport-https ca-certificates curl gnupg software-properties-common lsb-release"
"curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
"echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"
"sudo apt-get update"
"sudo apt-get install -y docker-ce docker-ce-cli containerd.io"
"echo '******************Testing Docker******************'"
"sudo docker version"
"sudo systemctl status docker --no-pager"
"echo '****************** Installing Apache ******************'"
"sudo apt install -y apache2"
"sudo systemctl start apache2"
"sudo systemctl status apache2 --no-pager"
"*************** Pulling Image and Running Container **************"
"docker pull erniepy/dwgettingstarted_web"
"sudo chown -R ubuntu /var/run/docker.sock"
"docker run -p 8080:8080 -d erniepy/dwgettingstarted_web"
"echo '****************** Adding index.html ******************'"
"sudo chown -R ubuntu /var/www/html/"
"echo 'AppServer' >/var/www/html/index.html"